name: CI Pipeline

on:
  push:
    branches:
      - main
      - 5-test-suite
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-qt

      - name: Run tests
        run: xvfb-run pytest -ra -q --tb=short --disable-warnings --maxfail=1 --cov=src --cov-report=xml --cov-report=html --cov-fail-under=80 tests/ > result.log; tail -n 20 result.log